YemekHanem/ProjeYemek/Models/Slider.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int ID { get; set; }
        public byte[] SliderFoto { get; set; }
        public string SliderText { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string ResimYolu { get; set; }
    }
}

YemekHanem/ProjeYemek/Areas/Admin/Controllers/SliderController.cs
using ProjeYemek.Areas.Admin.Models;
using ProjeYemek.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeYemek.Areas.Admin.Controllers
{
    public class SliderController : AdminController
    {
        projeyemekEntities db = new projeyemekEntities();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var model=db.Slider.OrderByDescending(x=>x.ID).ToList();
            return View(model);
        }
        public ActionResult Add()
        {
            return View();
        }


        const string imageFolderPath = "~/Content/slider-images/";
        /// <summary>
        /// Post ile gelen model bu metodda işlenir.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddSlider(SliderModel model)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //Dosya kaydetme
                if (model.SliderFoto != null && model.SliderFoto.ContentLength > 0)
                {
                    fileName = model.SliderFoto.FileName;
                    var path = Path.Combine(Server.MapPath(imageFolderPath), fileName);
                    model.SliderFoto.SaveAs(path);
                }

                //EF nesnesi oluşturma
                Slider slider = new Slider();
                slider.BaslangicTarihi = model.BaslangicTarihi;
                slider.BitisTarihi = model.BitisTarihi;
                slider.SliderText = model.SliderText;
                slider.ResimYolu = imageFolderPath + fileName;

                db.Slider.Add(slider);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Slider.Find(id);
            //db.Slider.FirstOrDefault(x => x.ID == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Slider model)
        {
            if (ModelState.IsValid)
            {
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

YemekHanem/ProjeYemek/Areas/Admin/Views/Slider/Add.cshtml
@model ProjeYemek.Areas.Admin.Models.SliderModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                   <b><center><h3>~~~~~~ Yeni Slider Ekleme ~~~~~~</h3></center></b> 
                </div>
                @using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    <div class="panel-body">
                        <h3>Basic Form Elements</h3>
                        <p>Try resizing the window to see how the form adapts at smaller screen sizes!</p>
                        <br>
                        <div class="form-group">
                            @Html.LabelFor(m => m.SliderText, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.SliderText, new { @class = "form-control", placeholder = "Slider Yazısı" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.BaslangicTarihi, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BaslangicTarihi, new { @class = "form-control datepicker", placeholder = "Başlangıç Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.BitisTarihi, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.BitisTarihi, new { @class = "form-control datepicker", placeholder = "Bitiş Tarihi" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.SliderFoto, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.SliderFoto, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button class="btn-primary btn">Submit</button>
                                    <button class="btn-default btn">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section pluginscss
{
    <link rel='stylesheet' type='text/css' href='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
}
@section jsplugins
{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
}
@section scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({
            format: 'mm.dd.yyyy'
        });
    </script>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekHanem/ProjeYemek/Areas/Admin/Views/Slider/Delete.cshtml
@model ProjeYemek.Models.Slider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h2>Delete</h2>
Silmek istediğinize emin misiniz?
<br />
@Model.SliderText
<br />
@Html.ActionLink("Kabul Ediyorum", "DeleteConfirm", new { id = Model.ID })
<br />
@Html.ActionLink("Kabul Etmiyorum", "Index")

YemekHanem/ProjeYemek/Areas/Admin/Views/Slider/Edit.cshtml
@model ProjeYemek.Models.Slider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Slider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SliderFoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderFoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderFoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SliderText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BaslangicTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangicTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BaslangicTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BitisTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BitisTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYolu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYolu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYolu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekHanem/ProjeYemek/Areas/Admin/Views/Slider/Index.cshtml
@model List<ProjeYemek.Models.Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<html lang="tr">
    <head>
        <title>Bootstrap Example</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="~/Content/style.css" rel="stylesheet" />
    </head>
    <body>

        <div class="row">
            <div class="col-md-12">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 clearfix">
                            <div class="btn-group pull-right">
                                <a href="javascript:;" class="btn btn-default btn-sm active">this week</a>
                                <a href="javascript:;" class="btn btn-default btn-sm ">previous week</a>
                            </div>
                            <div class="container">
                                <h2>SLIDERLAR SAYFASI</h2>
                                <p></p>
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Başlangıç Tarihi</th>
                                            <th>Bitiş Tarihi</th>
                                            <th>Text</th>
                                            <th>Resim Yolu</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@item.ID</td>
                                                <td>@item.BaslangicTarihi</td>
                                                <td>@item.BitisTarihi</td>
                                                <td>@item.SliderText</td>
                                                <td>@item.ResimYolu</td>
                                                <td>@Html.ActionLink("Düzenle", "Edit", "Slider", new { id = item.ID }, null) | @Html.ActionLink("Sil", "Delete", "Slider", new { id = item.ID }, null) </td>
                                            </tr>
                                        }
                                    </tbody>
                               </table>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div id="site-statistics" style="height:250px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>                              