YemekHanem/ProjeYemek/Models/Tatlilar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tatlilar
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<System.DateTime> Zaman { get; set; }
        public string PisirmeSuresi { get; set; }
        public string KisiAdedi { get; set; }
        public string Tarif { get; set; }
        public byte[] Foto { get; set; }
    }
}

YemekHanem/ProjeYemek/Areas/Admin/Controllers/TatlilarController.cs
using ProjeYemek.Areas.Admin.Models;
using ProjeYemek.Models;
using ProjeYemek.Areas.Admin.Controllers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeYemek.Areas.Admin.Controllers
{
    public class TatlilarController : AdminController
    {
        projeyemekEntities db = new projeyemekEntities();
        // GET: Admin/Tatlilar
        public ActionResult Index()
        {
            var model = db.Tatlilar.ToList();
            return View(model);
        }
        public ActionResult Add()
        {
            return View();
        }
        const string imageFolderPath = "/Content/images/";
        public ActionResult AddTatli(TatlilarModel model)
        {
            if (ModelState.IsValid)
            {

                string fileName = string.Empty;
                //Dosya kaydetme
                if (model.Foto != null && model.Foto.ContentLength > 0)
                {
                    fileName = model.Foto.FileName;
                    var path = Path.Combine(Server.MapPath("~" + imageFolderPath), fileName);
                    model.Foto.SaveAs(path);
                }


                //EF nesnesi oluşturma
                Tatlilar tatli = new Tatlilar();
                tatli.KisiAdedi = model.KisiAdedi;
                tatli.PisirmeSuresi = model.PisirmeSuresi;
                tatli.Zaman = model.Zaman;
                tatli.Baslik = model.Baslik;
                tatli.Tarif = model.Tarif;
                tatli.ResimYolu = imageFolderPath + fileName;

                db.Tatlilar.Add(tatli);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Tatlilar.Find(id);
            //db.Tatlilar.FirstOrDefault(x => x.ID == id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Tatlilar model)
        {
            if (ModelState.IsValid)
            {
                db.Tatlilar.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Tatlilar.Find(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Tatlilar.Find(id);
            db.Tatlilar.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

YemekHanem/ProjeYemek/Areas/Admin/Views/Tatlilar/Add.cshtml
@model ProjeYemek.Areas.Admin.Models.TatlilarModel
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                   <b><center><h3>~~~~~~ Yeni Tatlı Ekleme ~~~~~~</h3></center></b> 
                </div>
                @using (Html.BeginForm("AddTatli", "Tatlilar", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    <div class="panel-body">
                        <br>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Baslik, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Baslik, new { @class = "form-control"})
                            </div>
                            @*<div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>*@
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.KisiAdedi, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.KisiAdedi, new { @class = "form-control datepicker"})
                            </div>
                            @*<div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>*@
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.PisirmeSuresi, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.PisirmeSuresi, new { @class = "form-control datepicker",})
                            </div>
                            @*<div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>*@
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Tarif, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Tarif, new { @class = "form-control datepicker", })
                            </div>
                            @*<div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>*@
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Zaman, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Zaman, new { @class = "form-control datepicker" })
                            </div>
                            @*<div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>*@
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Foto, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Foto, new { @class = "form-control", placeholder = "Resim Yolu Giriniz", type = "file" })
                            </div>
                        </div>

                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <div class="btn-toolbar">
                                    <button class="btn-primary btn">Submit</button>
                                    <button class="btn-default btn">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section pluginscss
{
    <link rel='stylesheet' type='text/css' href='~/Content/jquery.ui.timepicker.css' />
}
@section jsplugins
{
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script>
}
@section scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({
            format: 'mm.dd.yyyy'
        });
    </script>
}

YemekHanem/ProjeYemek/Areas/Admin/Views/Tatlilar/Delete.cshtml
@model ProjeYemek.Models.Tatlilar

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h2>Delete</h2>
Silmek istediğinize emin misiniz?
<br />
@Model.Baslik
<br />
@Html.ActionLink("Kabul Ediyorum", "DeleteConfirm", new { id = Model.ID })
<br />
@Html.ActionLink("Kabul Etmiyorum", "Index")

YemekHanem/ProjeYemek/Areas/Admin/Views/Tatlilar/Edit.cshtml
@model ProjeYemek.Models.Tatlilar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tatlilar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYolu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYolu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYolu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zaman, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zaman, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zaman, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PisirmeSuresi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PisirmeSuresi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PisirmeSuresi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KisiAdedi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KisiAdedi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KisiAdedi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarif, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekHanem/ProjeYemek/Areas/Admin/Views/Tatlilar/Index.cshtml
@model List<ProjeYemek.Models.Tatlilar>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<html lang="tr">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>

    <div class="row">
        <div class="col-md-12">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 clearfix">
                        <div class="btn-group pull-right">
                            <a href="javascript:;" class="btn btn-default btn-sm active">this week</a>
                            <a href="javascript:;" class="btn btn-default btn-sm ">previous week</a>
                        </div>
                        <div class="container">
                            <h2>TATLILAR SAYFASI</h2>
                            <p></p>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Zaman</th>
                                        <th>KisiAdedi</th>
                                        <th>PisirmeSuresi</th>
                                        <th>ResimYolu</th>
                                        <th>Tarif</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.ID</td>
                                            <td>@item.Zaman</td>
                                            <td>@item.KisiAdedi</td>
                                            <td>@item.PisirmeSuresi</td>
                                            <td>@item.ResimYolu</td>
                                            <td>@item.Tarif</td>
                                            <td>@Html.ActionLink("Düzenle", "Edit", "Tatlilar", new { id = item.ID }, null) | @Html.ActionLink("Sil", "Delete", "Tatlilar", new { id = item.ID }, null) </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div id="site-statistics" style="height:250px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>